version: '3.8'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - webui:/app/backend/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  rag-backend:
    build:
      context: ./rag-backend
    ports:
      - "8000:8000"
    volumes:
      - ./rag-backend/app:/app
    depends_on:
      - qdrant
      - ollama
    environment:
      OLLAMA_URL: http://ollama:11434
      QDRANT_URL: http://qdrant:6333
      COLLECTION_NAME: docs
    restart: unless-stopped


volumes:
  ollama:
  webui:
  qdrant_data:
